
# /Users/jamessar/Source/jmespath/jmespath/_lrtable.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb8\xc92\xd7\xa6^\xd7j\xee_n\xf2\t{\xb6\xef'
    
_lr_action_items = {'LBRACE':([0,19,20,],[2,2,2,]),'STAR':([0,1,17,19,20,],[3,8,8,3,3,]),'RBRACE':([13,14,16,33,35,36,37,],[-17,28,-13,-18,-12,-14,-19,]),'NUMBER':([0,1,17,19,20,22,],[4,11,11,4,4,32,]),'LBRACKET':([0,3,4,5,6,7,9,12,13,18,19,20,21,25,26,28,30,31,33,34,36,37,],[1,-2,-9,-4,-8,17,22,-7,-17,-3,1,1,-5,-11,-6,-10,17,17,-18,22,22,-19,]),'COMMA':([9,10,13,14,16,33,34,35,36,37,],[-16,24,-17,27,-13,-18,-15,-12,-14,-19,]),'COLON':([15,],[29,]),'RBRACKET':([1,8,9,10,11,13,17,32,33,34,37,],[12,21,-16,25,26,-17,12,37,-18,-15,-19,]),'IDENTIFIER':([0,1,2,19,20,23,24,27,29,],[6,13,15,6,6,33,13,15,13,]),'OR':([3,4,5,6,7,12,18,21,25,26,28,30,31,],[-2,-9,-4,-8,19,-7,-3,-5,-11,-6,-10,19,-1,]),'DOT':([3,4,5,6,7,9,12,13,18,21,25,26,28,30,31,33,34,36,37,],[-2,-9,-4,-8,20,23,-7,-17,-3,-5,-11,-6,-10,20,20,-18,23,23,-19,]),'$end':([3,4,5,6,7,12,18,21,25,26,28,30,31,],[-2,-9,-4,-8,0,-7,-3,-5,-11,-6,-10,-20,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'nonbranched-expr':([1,24,29,],[9,34,36,]),'nonbranched-exprs':([1,],[10,]),'keyval-expr':([2,27,],[16,35,]),'bracket-spec':([0,7,19,20,30,31,],[5,18,5,5,18,18,]),'expression':([0,19,20,],[7,30,31,]),'keyval-exprs':([2,],[14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression DOT expression','expression',3,'p_jmespath_subexpression','/Users/jamessar/Source/jmespath/jmespath/parser.py',53),
  ('expression -> STAR','expression',1,'p_jmespath_subexpression','/Users/jamessar/Source/jmespath/jmespath/parser.py',54),
  ('expression -> expression bracket-spec','expression',2,'p_jmespath_index','/Users/jamessar/Source/jmespath/jmespath/parser.py',64),
  ('expression -> bracket-spec','expression',1,'p_jmespath_index','/Users/jamessar/Source/jmespath/jmespath/parser.py',65),
  ('bracket-spec -> LBRACKET STAR RBRACKET','bracket-spec',3,'p_jmespath_bracket_specifier','/Users/jamessar/Source/jmespath/jmespath/parser.py',76),
  ('bracket-spec -> LBRACKET NUMBER RBRACKET','bracket-spec',3,'p_jmespath_bracket_specifier','/Users/jamessar/Source/jmespath/jmespath/parser.py',77),
  ('bracket-spec -> LBRACKET RBRACKET','bracket-spec',2,'p_jmespath_bracket_specifier','/Users/jamessar/Source/jmespath/jmespath/parser.py',78),
  ('expression -> IDENTIFIER','expression',1,'p_jmespath_identifier','/Users/jamessar/Source/jmespath/jmespath/parser.py',88),
  ('expression -> NUMBER','expression',1,'p_jmespath_identifier','/Users/jamessar/Source/jmespath/jmespath/parser.py',89),
  ('expression -> LBRACE keyval-exprs RBRACE','expression',3,'p_jmespath_multiselect','/Users/jamessar/Source/jmespath/jmespath/parser.py',94),
  ('expression -> LBRACKET nonbranched-exprs RBRACKET','expression',3,'p_jmespath_multiselect_list','/Users/jamessar/Source/jmespath/jmespath/parser.py',99),
  ('keyval-exprs -> keyval-exprs COMMA keyval-expr','keyval-exprs',3,'p_jmespath_keyval_exprs','/Users/jamessar/Source/jmespath/jmespath/parser.py',104),
  ('keyval-exprs -> keyval-expr','keyval-exprs',1,'p_jmespath_keyval_exprs','/Users/jamessar/Source/jmespath/jmespath/parser.py',105),
  ('keyval-expr -> IDENTIFIER COLON nonbranched-expr','keyval-expr',3,'p_jmespath_keyval_expr','/Users/jamessar/Source/jmespath/jmespath/parser.py',114),
  ('nonbranched-exprs -> nonbranched-exprs COMMA nonbranched-expr','nonbranched-exprs',3,'p_jmespath_multiselect_nonbranched_expressions','/Users/jamessar/Source/jmespath/jmespath/parser.py',119),
  ('nonbranched-exprs -> nonbranched-expr','nonbranched-exprs',1,'p_jmespath_multiselect_nonbranched_expressions','/Users/jamessar/Source/jmespath/jmespath/parser.py',120),
  ('nonbranched-expr -> IDENTIFIER','nonbranched-expr',1,'p_jmespath_nonbranched_expression','/Users/jamessar/Source/jmespath/jmespath/parser.py',129),
  ('nonbranched-expr -> nonbranched-expr DOT IDENTIFIER','nonbranched-expr',3,'p_jmespath_nonbranched_expression','/Users/jamessar/Source/jmespath/jmespath/parser.py',130),
  ('nonbranched-expr -> nonbranched-expr LBRACKET NUMBER RBRACKET','nonbranched-expr',4,'p_jmespath_nonbranched_expression','/Users/jamessar/Source/jmespath/jmespath/parser.py',131),
  ('expression -> expression OR expression','expression',3,'p_jmespath_or_expression','/Users/jamessar/Source/jmespath/jmespath/parser.py',143),
]
