name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14-dev"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pip==25.1.0
        pip install -r requirements.txt
        python -m build --wheel
        pip install dist/*.whl
    - name: Test with pytest
      run: |
        cd tests/ && python -m pytest --cov jmespath --cov-report term-missing
